### PR TITLE
Notebook that compares keyword extraction approaches on longevity papers

### PR DESCRIPTION
**Pull request by PrimozGodec**
This comparison was made for an article.

### CODE REVIEW

**Comment by PrimozGodec** [comment]
I am additionally appending a word cloud for those articles

Screenshot 2021-03-16 at 12 12 05

**Comment by djukicn** [comment]
There might be a reason for precision and recall being so low. If I'm not mistaken, this notebook originated from [SemEval evaluation](https://github.com/biolab/text-semantics/blob/f7f30197f15955efeba7b76756645870b33449ae/examples/04_09_specific_words_comparison_semeval.ipynb) where the ground truth keywords were already stemmed and the code kept them just as they are. In PubMed data, the keywords are not preprocessed but the notebook does stemming on text. Also, I'd recommend lemmatization instead of stemming because stemming might take away too much information and reduce the score achieved by embedding methods.

**Comment by ajdapretnar** [comment]
That's a good find. One must indeed be careful with preprocessing!

**Comment by PrimozGodec** [comment]
@djukicn thank you for your observation. I totally overlooked that true keywords are not preprocessed same as text. It is fixed now. 

Bellow, I am appending results produced with stemming and lemmatization. As you correctly assumed embedding method gives better results with lemmatization. I do not understand exactly what is the reason for that.

Stemming:
Screenshot 2021-03-28 at 15 40 32

Lemmatization:
Screenshot 2021-03-28 at 15 40 40

**Pull request merged**
